"""Application-wide constants."""

BATCH_SIZE = 50_000

DEFAULT_SCHEMA = "public"

CHECKPOINT_FILE = "checkpoints.json"

EXPORT_FOLDER = "exports"

SOURCE_DB = "POSTGRES"
TARGET_DB = "MYSQL"

CONNECTION_POOL_SIZE = 5
CONNECTION_MAX_OVERFLOW = 10
CONNECTION_RETRY_ATTEMPTS = 3
CONNECTION_RETRY_DELAY = 2.0

MIGRATION_STATUS_STARTED = "STARTED"
MIGRATION_STATUS_RUNNING = "RUNNING"
MIGRATION_STATUS_PAUSED = "PAUSED"
MIGRATION_STATUS_COMPLETED = "COMPLETED"
MIGRATION_STATUS_FAILED = "FAILED"
MIGRATION_STATUS_STOPPED = "STOPPED"

VALIDATION_PASS = "PASS"
VALIDATION_FAIL = "FAIL"
